# Generated by Django 5.2.15 on 2026-06-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=64)),
                ('source_system', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.importrun')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='regions.region')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'year'], name='indicators__region__5f7804_idx'), models.Index(fields=['indicator', 'year'], name='indicators__indicat_33aa08_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'indicator', 'year'), name='unique_indicator_value')],
            },
        ),
    ]
