# Generated by Django 5.2.15 on 2026-06-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('official_download', 'Official download'), ('opal_fallback', 'OPAL fallback'), ('manual_reference', 'Manual reference')], max_length=32)),
                ('url_or_path', models.TextField()),
                ('provider', models.CharField(max_length=255)),
                ('licence', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type'], name='catalog_sou_source__4b5681_idx'), models.Index(fields=['provider'], name='catalog_sou_provide_7b8abb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], default='started', max_length=16)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='catalog.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'status'], name='catalog_imp_source__e0925a_idx'), models.Index(fields=['started_at'], name='catalog_imp_started_99270b_idx')],
            },
        ),
    ]
