# Generated by Django 5.2.15 on 2026-06-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(max_length=128)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('accident_type', models.CharField(blank=True, max_length=32)),
                ('light_condition', models.CharField(blank=True, max_length=32)),
                ('road_condition', models.CharField(blank=True, max_length=32)),
                ('is_bicycle', models.BooleanField(default=False)),
                ('is_car', models.BooleanField(default=False)),
                ('is_pedestrian', models.BooleanField(default=False)),
                ('is_motorcycle', models.BooleanField(default=False)),
                ('is_goods_vehicle', models.BooleanField(default=False)),
                ('is_other', models.BooleanField(default=False)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('district_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_accidents', to='regions.region')),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.importrun')),
                ('municipality_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipality_accidents', to='regions.region')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.source')),
                ('state_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_accidents', to='regions.region')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='accidents_a_year_eea51d_idx'), models.Index(fields=['year', 'state_region'], name='accidents_a_year_cdf2e7_idx'), models.Index(fields=['year', 'district_region'], name='accidents_a_year_cd9a7c_idx'), models.Index(fields=['category'], name='accidents_a_categor_16fbb9_idx'), models.Index(fields=['is_pedestrian'], name='accidents_a_is_pede_9f09d3_idx'), models.Index(fields=['is_bicycle'], name='accidents_a_is_bicy_c8a8fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_event_id'), name='unique_accident_per_source_event')],
            },
        ),
        migrations.CreateModel(
            name='AccidentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('region_level', models.CharField(max_length=32)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('participant', models.CharField(blank=True, max_length=32)),
                ('accident_count', models.PositiveIntegerField()),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'region_level'], name='accidents_a_year_4280aa_idx'), models.Index(fields=['year', 'region'], name='accidents_a_year_45729f_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'region', 'category', 'participant'), name='unique_accident_summary')],
            },
        ),
    ]
