# Generated by Django 5.2.15 on 2026-06-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ags', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('state', 'State'), ('district', 'District'), ('municipality', 'Municipality')], max_length=32)),
                ('state_code', models.CharField(blank=True, max_length=8)),
                ('state_name', models.CharField(blank=True, max_length=255)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('geometry_source_id', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='regions.region')),
            ],
            options={
                'indexes': [models.Index(fields=['ags'], name='regions_reg_ags_9a23db_idx'), models.Index(fields=['level'], name='regions_reg_level_d2c0f0_idx'), models.Index(fields=['state_code', 'level'], name='regions_reg_state_c_005b4f_idx')],
            },
        ),
    ]
